language: go
go:
  - 1.4.2

env:
  global:
    - CODECOV_TOKEN=8622fd8a-c028-4d82-b265-b397b639eac8

sudo: false

notifications:
  slack: empatica:zrdUm3NbXvqaxSjOGaIvGJsp

script:
- go test -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)
